### ISSUE TITLE
A Problem on Framework4.6.1 with  Exception  "未能加载文件或程序集 Nito.AsyncEx.Context,Version1.1.0.0"

### ISSUE THREAD

**Issue by wei-king** [SkyAPM/SkyAPM-dotnet#320] opened 2020-08-19 02:06 UTC
提示“未能加载程序集Nito.AsyncEx.Context,Version=1.1.0.0” 或它的某个依赖项，需要强名称的程序集
![微信截图_20200819100519](https://user-images.githubusercontent.com/26075344/90583765-9d4bef00-e203-11ea-885c-d3161e982bbb.png)

**Comment by ElderJames** [comment] 2020-08-25 01:37
Thank you for contacting us @wei-king ,
This works fine in our ASP.NET example. Please reinstall the dependency packages.

**Comment by wei-king** [comment] 2020-08-25 02:15
> 
> 
> Thank you for contacting us @wei-king ,
> This works fine in our ASP.NET example. Please reinstall the dependency packages.
Can you send me your  dependency packages ? 
because i try much times with github code but not work, thinks

**Comment by wei-king** [comment] 2020-08-25 02:21
i`m very happy for your reply！

Can you send me your  dependency packages ?
 because i try much times with github code but not work, thinks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-dotnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 上午9:37
收件人:&nbsp;"SkyAPM/SkyAPM-dotnet"<SkyAPM-dotnet@noreply.github.com&gt;;
抄送:&nbsp;"祗爱の紫冰"<823557916@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-dotnet] A Problem on Framework4.6.1 with  Exception  "未能加载文件或程序集 Nito.AsyncEx.Context,Version1.1.0.0" (#320)





 
Thank you for contacting us @wei-king ,
 This works fine in our ASP.NET example. Please reinstall the dependency packages.

**Comment by snakorse** [comment] 2020-10-28 10:33
@wei-king  I can't reproduce the problem too and I will go close this issue, feel free to reopen it if you have any following questions.

**Closed by snakorse** 2020-10-28 10:33 UTC
