### ISSUE TITLE
when the skyapm suport the .netfranwork can use ?

### ISSUE THREAD

**Issue by DavidChild** [SkyAPM/SkyAPM-dotnet#303] opened 2020-06-12 09:38 UTC
now, i want to use  the skyapm-dotnet in my more project. but    when i used  the laste skyapm-dotnet  refrence in my  webapi project  witch is used  .netframework 4.6.1  ,  that throw  exception.  

i have more and more .netframework webapi and more and more .netcore webapi services . that ,I all want to use the skywalking now . 

hope the skyapm-dotnet suport the .netframewrok 4.6.1 soon .Tks.

**Comment by zeaposs** [comment] 2021-01-22 14:39
Could you provide additional information? Type of the exception and version of the agent would be very useful.
I'm assuming that this can be duplicate of #300.

**Comment by snakorse** [comment] 2021-03-15 11:42
With version 1.2.0 or higher, should works well with .netframework 4.6.1. This issue gona be closed, but feel free to submit another issue if you have any problems.

**Closed by snakorse** 2021-03-15 11:42 UTC
