### ISSUE TITLE
Failed to load file or assembly“ Nito.AsyncEx.Context , version = 1.1.0.0, culture = neutral, publickeytoken = null "or one of its dependencies. A strongly named assembly is required

### ISSUE THREAD

**Issue by GavinHome** [SkyAPM/SkyAPM-dotnet#373] opened 2021-01-20 02:39 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Bug

Failed to load file or assembly“ Nito.AsyncEx.Context , version = 1.1.0.0, culture = neutral, publickeytoken = null "or one of its dependencies. A strongly named assembly is required

![image](https://user-images.githubusercontent.com/5460850/105118792-01a01100-5b0a-11eb-8543-629565441c79.png)

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
- SkyAPM.Agent.AspNet 0.9.0
- .NET Framework 4.6.1

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

There is a demo application:

[SkyWalkingDemo.zip](https://github.com/SkyAPM/SkyAPM-dotnet/files/5839783/SkyWalkingDemo.zip)

**Comment by zeaposs** [comment] 2021-01-20 09:11
Duplicate of #300.
This bug should be gone in version 1.2.0.

**Closed** 2021-01-20 09:24 UTC
